title: "swordfischer.io"
name: "swordfischer"
description: >
baseurl: "/"
url: "https://swordfischer.github.io"

remote_theme: jekyll/minima

minima:
  skin: dark

collections:
  cyberdefenders:
    name: 'Cyber Defenders'
    output: true
    permalink: /writeups/:collection/:name
    image: /img/cd/:name/logo.webp
    logo: /img/cd/logo.png
  hackthebox:
    name: 'Hack the Box'
    output: true
    permalink: /writeups/:collection/:name
    image: /img/htb/:name/logo.png
    logo: /img/htb/logo.png